version: "3.7"

services:
  # PHP
  php:
    build:
      context: ./docker/php-cli
    volumes:
      - .:/app:z
    env_file:
      - ./docker/xdebug/xdebug.env
    entrypoint: ["php"]

  # Composer
  composer:
    image: composer
    volumes:
      - .:/app:z
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache:z
    working_dir: /app

  # Node with NPM/Yarn/npx
  node:
    image: node
    volumes:
      - .:/app:z
    working_dir: /app

  # phpcs
  phpcs:
    image: herloct/phpcs
    command: ["--standard=PSR1,PSR2", "--ignore=*/vendor/,*/tests/,database/,app/bootstrap/,public/", "--colors", "."]
    volumes:
      - .:/app:z
    working_dir: /app
